engines:
  pep8:
    enabled: true

  markdownlint:
    enabled: true

  sonar-python:
    enabled: true

exclude_patterns:
  - "**/test/"
  - "**/.venv/"
  - "**/.vscode/"
  - "**/dist/"
  - "**/django_http2_push.egg-info/"
  - "**/build/"
  - "**/.tox/"